baseURL = "https://mundara-website-2fuzgys2z-nak0xs-projects.vercel.app/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "PaperMod"

[params]
  homeInfoParams = { Title = "Hi, I'm PaperMod", Content = "Welcome to my blog" }

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"
